set guioptions-=T         " Remove toolbar
set guioptions-=r         " Remove right scrollbar
set guioptions-=l         " Remove left scrollbar
set guioptions-=L         " Remove left scrollbar
set guioptions-=e         " text tabs
set guifont=Menlo:h12    " font size
color codeschool
set vb
