set guioptions-=T         " Remove toolbar
set guioptions-=r         " Remove right scrollbar
set guioptions-=l         " Remove left scrollbar
set guioptions-=L         " Remove left scrollbar
set lines=60 columns=100  " UI size
set guifont=Monaco:h12    " font size
