# Customize to your needs...
LATEX=/usr/texbin
X11=/usr/X11/bin
export CLASSPATH=$CLASSPATH:/usr/local/Cellar/clojure-contrib/1.2.0/clojure-contrib.jar

# putting it all together
export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/sbin:$PATH
export PATH=$PATH:$LATEX:$X11:~/dotfiles/bin
export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH
export NODE_PATH=/usr/local/lib/node_modules

# history
HISTFILE=$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt hist_ignore_dups
setopt share_history
setopt hist_expire_dups_first
setopt hist_ignore_space

# key bindings
bindkey '^[^[[D' backward-word
bindkey '^[^[[C' forward-word
bindkey '^[[5D' beginning-of-line
bindkey '^[[5C' end-of-line
bindkey '^[[3~' delete-char
bindkey '^[^N' newtab
bindkey '^?' backward-delete-char
bindkey '^r' history-incremental-search-backward
# up and down search in history
bindkey '^[[A' up-line-or-search
bindkey '^[[B' down-line-or-search

# load theme
source ~/.zsh/theme.zsh

# load aliases
source ~/.zsh/aliases.zsh

if [ -e ~/.zsh/work ]; then
  for i in `ls ~/.zsh/work`; do
    source ~/.zsh/work/$i
  done
fi

# This loads RVM into a shell session.
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"
rvm default
