# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set to the name theme to load.
# Look in ~/.oh-my-zsh/themes/
export ZSH_THEME="dstufft"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
    plugins=(git)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
LATEX=/usr/texbin
X11=/usr/X11/bin
CABAL=/Users/max/.cabal/bin
ANDROID=/Applications/eclipse/android-sdk-mac_x86/tools
PYTHON=/usr/local/Cellar/python/2.7.1/bin/

# putting it all together
export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/sbin:$PATH
export PATH=$PATH:$CABAL:$LATEX:$X11:$ANDROID:$PYTHON:~/dotfiles/bin

# vi bindings..
# bindkey -v

bindkey '^[^[[D' backward-word
bindkey '^[^[[C' forward-word
bindkey '^[[5D' beginning-of-line
bindkey '^[[5C' end-of-line
bindkey '^[[3~' delete-char
bindkey '^[^N' newtab
bindkey '^?' backward-delete-char

# This loads RVM into a shell session.
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"  
