# Customize to your needs...
export RBENV_ROOT=/usr/local/var/rbenv
export GOPATH=$HOME/code/go
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:~/dotfiles/bin
export PATH=/usr/local/bin:$PATH
export CFLAGS="-march=nocona -O2 -pipe"
export EDITOR="vim"
bindkey -e

# history
HISTFILE=$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt hist_ignore_dups
setopt share_history
setopt hist_expire_dups_first
setopt hist_ignore_space

# key bindings
bindkey '^[^[[D' backward-word
bindkey '^[^[[C' forward-word
bindkey '^[[5D' beginning-of-line
bindkey '^[[5C' end-of-line
bindkey '^[[3~' delete-char
bindkey '^[^N' newtab
bindkey '^?' backward-delete-char
bindkey '^r' history-incremental-search-backward
# up and down search in history
bindkey '^[[A' up-line-or-search
bindkey '^[[B' down-line-or-search

# select word style
autoload -U select-word-style
select-word-style bash

# load theme
source ~/.zsh/theme.zsh

# load aliases
source ~/.zsh/aliases.zsh

if [ -e ~/.zsh/work ]; then
  for i in `ls ~/.zsh/work`; do
    source ~/.zsh/work/$i
  done
fi

if which rbenv > /dev/null; then eval "$(rbenv init - zsh)"; fi
